In [ ]:
import numpy as np

In [ ]:
l = np.random.rand(100, 10)
y = np.random.randint(10, size=100)
idx = np.hstack([np.expand_dims(np.arange(len(l)), axis=1), np.expand_dims(y, axis=1)])

In [ ]:
(l - np.expand_dims(l[np.arange(len(l)), y], axis=1))

In [ ]:
l

In [ ]:
np.expand_dims(l[np.arange(len(l)), y], axis=1)

In [27]:
l = np.random.rand(3, 2)

In [36]:
l

array([[-1.        ,  0.57005469],
       [ 0.74510235, -1.        ],
       [-1.        ,  0.52573032]])

In [30]:
l[np.arange(3), np.array([0,1,0])] = -1

In [32]:
a = np.array([1,2,3])

In [33]:
a

array([1, 2, 3])

In [35]:
l / np.expand_dims(a, 1)

array([[-1.        ,  0.57005469],
       [ 0.37255117, -0.5       ],
       [-0.33333333,  0.17524344]])

In [37]:
a

array([1, 2, 3])

In [38]:
b = np.array([2, 3])

In [48]:
np.expand_dims(a, 1) * b

array([[2, 3],
       [4, 6],
       [6, 9]])

In [51]:
a = np.array([-1, 3, 4, -2])
b = np.array([1,2,3,4])
b * (a >= 0)

array([0, 2, 3, 0])

In [57]:
l[np.arange(3), np.array([1,0,1])][:, np.newaxis]

array([[ 0.57005469],
       [ 0.74510235],
       [ 0.52573032]])

In [58]:
range(10, 1, -1)

[10, 9, 8, 7, 6, 5, 4, 3, 2]

In [59]:
a = np.random.randn(4,4)

In [72]:
a

array([[ 1.63264141,  0.70322996, -0.39579976, -0.41460706],
       [-2.20542275,  0.        , -0.33996665,  0.27732707],
       [-1.72583067,  0.        ,  1.35076866,  0.70473944],
       [ 0.        ,  2.08349233, -0.99356802,  0.33515009]])

In [62]:
np.maximum(0, a)

array([[ 1.63264141,  0.70322996,  0.        ,  0.        ],
       [ 0.        ,  1.40447585,  0.        ,  0.27732707],
       [ 0.        ,  0.62985153,  1.35076866,  0.70473944],
       [ 0.31633482,  2.08349233,  0.        ,  0.33515009]])

In [74]:
b = np.random.randn(4,4)

In [75]:
b

array([[ 0.21810503, -1.01745093, -0.43231756,  0.76115637],
       [ 0.16978245,  0.37972898,  0.41832836,  0.48427405],
       [ 0.39951518,  1.17099092,  0.90655476, -0.76616891],
       [ 0.14891425,  0.6786803 ,  0.95105295, -0.52094113]])

In [76]:
a * (b >= 0)

array([[ 1.63264141,  0.        , -0.        , -0.41460706],
       [-2.20542275,  0.        , -0.33996665,  0.27732707],
       [-1.72583067,  0.        ,  1.35076866,  0.        ],
       [ 0.        ,  2.08349233, -0.99356802,  0.        ]])

In [77]:
a

array([[ 1.63264141,  0.70322996, -0.39579976, -0.41460706],
       [-2.20542275,  0.        , -0.33996665,  0.27732707],
       [-1.72583067,  0.        ,  1.35076866,  0.70473944],
       [ 0.        ,  2.08349233, -0.99356802,  0.33515009]])

In [84]:
(np.random.rand(*a.shape) < 0.7) / 0.7

array([[ 1.42857143,  1.42857143,  1.42857143,  0.        ],
       [ 0.        ,  1.42857143,  0.        ,  1.42857143],
       [ 1.42857143,  1.42857143,  1.42857143,  1.42857143],
       [ 1.42857143,  0.        ,  1.42857143,  0.        ]])

In [85]:
np.logspace(0, 4, num=20)

array([  1.00000000e+00,   1.62377674e+00,   2.63665090e+00,
         4.28133240e+00,   6.95192796e+00,   1.12883789e+01,
         1.83298071e+01,   2.97635144e+01,   4.83293024e+01,
         7.84759970e+01,   1.27427499e+02,   2.06913808e+02,
         3.35981829e+02,   5.45559478e+02,   8.85866790e+02,
         1.43844989e+03,   2.33572147e+03,   3.79269019e+03,
         6.15848211e+03,   1.00000000e+04])

In [82]:
l.pop()

4

In [96]:
t = np.random.rand(3,3,3,3)

In [97]:
t

array([[[[ 0.94131611,  0.28939157,  0.29011614],
         [ 0.80872317,  0.23796201,  0.97141889],
         [ 0.77126137,  0.49579777,  0.56812862]],

        [[ 0.88841477,  0.58508253,  0.28591528],
         [ 0.62189446,  0.98265269,  0.52184416],
         [ 0.42962397,  0.38848529,  0.15478447]],

        [[ 0.49142114,  0.613577  ,  0.00678973],
         [ 0.48258183,  0.24890654,  0.51149887],
         [ 0.68793864,  0.29465061,  0.32809506]]],


       [[[ 0.88482712,  0.00388314,  0.15675285],
         [ 0.0334039 ,  0.4934724 ,  0.19666019],
         [ 0.93661533,  0.78127842,  0.68116399]],

        [[ 0.78539591,  0.67314166,  0.93980553],
         [ 0.59948132,  0.27530952,  0.94966898],
         [ 0.08774375,  0.72857825,  0.88247585]],

        [[ 0.79916398,  0.77673843,  0.04234804],
         [ 0.77624586,  0.91910345,  0.40335783],
         [ 0.32590244,  0.96507486,  0.91155843]]],


       [[[ 0.1959493 ,  0.47653729,  0.90091161],
         [ 0.32781063,  0.60774697

In [98]:
np.pad(t, ((0, 0), (0, 0), (1,1), (1,1)), 'constant', constant_values=0)

array([[[[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.94131611,  0.28939157,  0.29011614,  0.        ],
         [ 0.        ,  0.80872317,  0.23796201,  0.97141889,  0.        ],
         [ 0.        ,  0.77126137,  0.49579777,  0.56812862,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]],

        [[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.88841477,  0.58508253,  0.28591528,  0.        ],
         [ 0.        ,  0.62189446,  0.98265269,  0.52184416,  0.        ],
         [ 0.        ,  0.42962397,  0.38848529,  0.15478447,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]],

        [[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.49142114,  0.613577  ,  0.00678973,  0.        ],
         [ 0.        ,  0.48258183,  0.24890654,  0.51149887,  0.        ],
        

In [103]:
x = np.random.rand(3, 3, 3, 3)

In [104]:
w = np.random.rand(3, 2, 2)

In [110]:
np.sum((x[:, :, 1:3, 1:3] * w), axis=(1,2,3))

array([ 3.99677825,  2.83686494,  4.42679518])

In [111]:
t = np.arange(4).reshape(2,2)

In [112]:
t

array([[0, 1],
       [2, 3]])

In [116]:
np.flip(np.flip(t, 0), 1)

array([[3, 2],
       [1, 0]])

In [117]:
t

array([[0, 1],
       [2, 3]])

In [121]:
np.argmax(w)

5

In [132]:
np.random.randn(2,2)

array([[ 0.14736168,  0.31689311],
       [-0.45058268, -1.96346807]])

In [129]:
np.zeros((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [133]:
np.log(10)

2.3025850929940459

In [134]:
np.var(w)

0.087481749295711023

In [135]:
np.std(w)

0.29577313822541595