In [1]:
import numpy as np

In [2]:
l = np.random.rand(100, 10)
y = np.random.randint(10, size=100)
idx = np.hstack([np.expand_dims(np.arange(len(l)), axis=1), np.expand_dims(y, axis=1)])

In [ ]:
(l - np.expand_dims(l[np.arange(len(l)), y], axis=1))

In [ ]:
l

In [ ]:
np.expand_dims(l[np.arange(len(l)), y], axis=1)

In [ ]:
l = np.random.rand(3, 2)

In [ ]:
l

In [ ]:
l[np.arange(3), np.array([0,1,0])] = -1

In [ ]:
a = np.array([1,2,3])

In [ ]:
a

In [ ]:
l / np.expand_dims(a, 1)

In [ ]:
a

In [ ]:
b = np.array([2, 3])

In [ ]:
np.expand_dims(a, 1) * b

In [ ]:
a = np.array([-1, 3, 4, -2])
b = np.array([1,2,3,4])
b * (a >= 0)

In [ ]:
l[np.arange(3), np.array([1,0,1])][:, np.newaxis]

In [ ]:
range(10, 1, -1)

In [ ]:
a = np.random.randn(4,4)

In [ ]:
a

In [ ]:
np.maximum(0, a)

In [ ]:
b = np.random.randn(4,4)

In [ ]:
b

In [ ]:
a * (b >= 0)

In [ ]:
a

In [ ]:
(np.random.rand(*a.shape) < 0.7) / 0.7

In [ ]:
np.logspace(0, 4, num=20)

In [ ]:
l.pop()

In [ ]:
t = np.random.rand(3,3,3,3)

In [ ]:
t

In [ ]:
np.pad(t, ((0, 0), (0, 0), (1,1), (1,1)), 'constant', constant_values=0)

In [ ]:
x = np.random.rand(3, 3, 3, 3)

In [ ]:
w = np.random.rand(3, 2, 2)

In [ ]:
np.sum((x[:, :, 1:3, 1:3] * w), axis=(1,2,3))

In [ ]:
t = np.arange(4).reshape(2,2)

In [ ]:
t

In [ ]:
np.flip(np.flip(t, 0), 1)

In [ ]:
t

In [ ]:
np.argmax(w)

In [ ]:
np.random.randn(2,2)

In [ ]:
np.zeros((2,2))

In [ ]:
np.log(10)

In [ ]:
np.var(w)

In [ ]:
np.std(w)

In [ ]:
import math

In [ ]:
math.log(10, 3)

In [ ]:
19*19, 170*2.096

In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model, decomposition

In [ ]:
x1 = np.arange(0, 10, .2)
x2 = x1 + np.random.normal(loc=0, scale = 1, size=len(x1))
X = np.c_[(x1, x2)]
good = (x1 > 5) | (x2 > 5)
bad = ~good
plt.clf()
fig = plt.figure(num=None, figsize=(10, 4))
plt.subplot(121)

title = "Original feature space"
plt.title(title)
plt.xlabel("$X_1$")
plt.ylabel("$X_2$")

x1 = np.arange(0, 10, .2)
x2 = x1 + np.random.normal(loc=0, scale=1, size=len(x1))

good = (x1 > 5) | (x2 > 5)
bad = ~good

x1g = x1[good]
x2g = x2[good]
plt.scatter(x1g, x2g, edgecolor="blue", facecolor="blue")

x1b = x1[bad]
x2b = x2[bad]
plt.scatter(x1b, x2b, edgecolor="red", facecolor="white")

plt.grid(True)

plt.subplot(122)

X = np.c_[(x1, x2)]

pca = decomposition.PCA(n_components=1)
Xtrans = pca.fit_transform(X)

Xg = Xtrans[good]
Xb = Xtrans[bad]

# plt.scatter(
#     Xg[:, 0], np.zeros(len(Xg)), edgecolor="blue", facecolor="blue")
# plt.scatter(
#     Xb[:, 0], np.zeros(len(Xb)), edgecolor="red", facecolor="white")
# title = "Transformed feature space"
# plt.title(title)
# plt.xlabel("$X'$")
# fig.axes[1].get_yaxis().set_visible(False)

# print(pca.explained_variance_ratio_)

# plt.grid(True)

# filename = "pca_demo_1.png"
#     plt.savefig(os.path.join(CHART_DIR, filename), bbox_inches="tight")

In [1]:
range(9, -1, -1)

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [4]:
import numpy as np
w = np.random.randn(5, 3)

In [5]:
w

array([[-2.5051504 , -0.36533533,  1.48259802],
       [ 0.78221413,  1.55746249, -0.49298349],
       [-0.96030484, -1.03367919,  1.83642095],
       [-1.03390661,  1.29644087,  1.28114641],
       [ 0.25302934, -0.9543367 ,  1.35611208]])

In [6]:
x = np.array([[1, 3], [2, 4]])

In [7]:
x

array([[1, 3],
       [2, 4]])

In [11]:
w[x]

array([[[ 0.78221413,  1.55746249, -0.49298349],
        [-1.03390661,  1.29644087,  1.28114641]],

       [[-0.96030484, -1.03367919,  1.83642095],
        [ 0.25302934, -0.9543367 ,  1.35611208]]])

In [13]:
np.argmax(w, axis=1)

array([2, 1, 2, 1, 2])

In [14]:
np.linspace(0.2, 0.5, 10)

array([ 0.2       ,  0.23333333,  0.26666667,  0.3       ,  0.33333333,
        0.36666667,  0.4       ,  0.43333333,  0.46666667,  0.5       ])

In [4]:
int(1.63432)

1

In [11]:
import random
x = range(62)
random.shuffle(x)
m = zip(range(62), x)

AttributeError: 'module' object has no attribute 'map'